# Generated by Django 3.1.7 on 2021-03-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='1', max_length=120),
            preserve_default=False,
        ),
    ]
