# Generated by Django 3.1.7 on 2021-03-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210326_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
