# Generated by Django 3.1.7 on 2021-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-04'),
            preserve_default=False,
        ),
    ]
